# Generated by Django 5.1.3 on 2024-11-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_alter_usuario_options_producto_stock_offline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='metodo_venta',
            field=models.CharField(choices=[('unidad', 'Por Unidad'), ('kilo', 'Por Peso')], default='unidad', max_length=10),
        ),
    ]
