# Generated by Django 5.1.3 on 2024-11-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_producto_metodo_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock_offline',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock_online',
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(choices=[(1, 'Online'), (2, 'Presencial')], default=1),
        ),
    ]
