# Generated by Django 5.1.3 on 2024-12-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_empresa_remove_venta_cantidad_remove_venta_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='empresa',
        ),
        migrations.AddField(
            model_name='usuario',
            name='identificacion_terreno',
            field=models.CharField(blank=True, help_text='Identificador único del terreno de producción.', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre_propietario',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre_terreno',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='token_social',
            field=models.TextField(blank=True, null=True),
        ),
    ]
