# Generated by Django 5.1.4 on 2024-12-14 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_remove_usuario_empresa_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empresa',
        ),
        migrations.RemoveField(
            model_name='boleta',
            name='venta',
        ),
    ]
