# Generated by Django 5.1.4 on 2024-12-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0009_remove_anuncio_productor_remove_ubicacion_productor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
