# Generated by Django 5.1.4 on 2024-12-14 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0010_alter_producto_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='empresa',
        ),
        migrations.AddField(
            model_name='venta',
            name='boleta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venta_asociada', to='aplicacion.boleta'),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='venta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boleta_asociada', to='aplicacion.venta'),
        ),
        migrations.AlterField(
            model_name='categoriaproducto',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.venta'),
        ),
        migrations.AlterField(
            model_name='eventoturistico',
            name='productor',
            field=models.ForeignKey(limit_choices_to={'rol': 'productor'}, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_productor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='producto',
            name='metodo_venta',
            field=models.CharField(choices=[('unidad', 'Por Unidad'), ('kilo', 'Por Peso')], default='unidad', max_length=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(choices=[(1, 'Online'), (2, 'Presencial')], default=1),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='descuento',
            field=models.DecimalField(decimal_places=2, help_text='Porcentaje de descuento', max_digits=5),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='identificacion_terreno',
            field=models.CharField(blank=True, help_text='Identificador único del terreno de producción.', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('compra', 'Compra'), ('visita', 'Visita'), ('feedback', 'Feedback')], max_length=50)),
                ('detalle', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('direccion', models.CharField(max_length=255)),
                ('productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
