# Generated by Django 5.1.4 on 2024-12-14 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0011_alter_usuario_options_remove_usuario_empresa_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empresa',
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='boleta',
            name='venta',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='identificacion_terreno',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre_propietario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre_terreno',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='boleta',
        ),
    ]
