# Generated by Django 5.2.1 on 2026-02-04 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0012_delete_empresa_alter_usuario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='venta',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='boleta', to='aplicacion.venta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boleta',
            name='fecha_emision',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='numero_boleta',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
