# Generated by Django 5.2.1 on 2026-02-06 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0013_boleta_venta_alter_boleta_fecha_emision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactorCarbono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100, unique=True)),
                ('co2_por_unidad', models.DecimalField(decimal_places=5, max_digits=10)),
                ('unidad', models.CharField(default='kg', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('porcentaje', 'Porcentaje'), ('monto_fijo', 'Monto Fijo')], default='porcentaje', max_length=15)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
                ('limite_uso', models.PositiveIntegerField(default=1)),
                ('conteo_uso', models.PositiveIntegerField(default=0)),
                ('productor', models.ForeignKey(blank=True, limit_choices_to={'rol': 'productor'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
