# Generated by Django 5.2.1 on 2026-02-06 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0014_factorcarbono_cupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cupon_aplicado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.cupon'),
        ),
        migrations.AddField(
            model_name='venta',
            name='descuento_cupon',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='huella_carbono_total',
            field=models.DecimalField(decimal_places=5, default=0.0, help_text='Total kg CO2', max_digits=10),
        ),
    ]
