# Generated by Django 5.2.1 on 2026-02-06 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0015_venta_cupon_aplicado_venta_descuento_cupon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='factor_carbono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.factorcarbono'),
        ),
    ]
