# Generated by Django 5.2.1 on 2026-02-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0017_tokenblacklist_fcmtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('fallido', 'Fallido'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='monto_comision',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='15% plataforma', max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='monto_neto_productor',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='85% productor', max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
