# Generated by Django 5.2.1 on 2026-02-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0018_venta_estado_pago_venta_monto_comision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='bio',
            field=models.TextField(blank=True, help_text='Breve biografía del productor', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sitio_web',
            field=models.URLField(blank=True, help_text='URL de sitio web o red social principal', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Número de WhatsApp para contacto directo', max_length=15, null=True),
        ),
    ]
