# Generated by Django 5.2.1 on 2026-02-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0019_usuario_bio_usuario_sitio_web_usuario_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('productor', 'Productor'), ('admin', 'Administrador')], db_index=True, default='cliente', max_length=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('fallido', 'Fallido'), ('reembolsado', 'Reembolsado')], db_index=True, default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
